# Generated by Django 5.0.6 on 2024-07-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Book',
                'db_table': 'book',
            },
        ),
    ]
